### PR TITLE
refactor check_rtsp script

### PR DESCRIPTION
**Pull request by bonuzzz**
changed checking port status to LISTEN because ESTABLISHED means that something connects to camera's rtsp port.
first rule is checking port
second rule is checking process existence
third rule is checking for locked process
probably we need to check for zombie process. I don't know here. I haven't deal with locked processes or hangs on camera.

### CODE REVIEW

**Comment by roleoroleo** [comment]
We cannot remove the check about ESTABLISHED sockets.
The watchdog was created to monitor the problem described in this issue:
https://github.com/roleoroleo/yi-hack-MStar/issues/85
In this case, the processes (h264grabber and rRTSPServer) are running but don't send stream to the client (therefore socket is established and cpu load is 0) and we need to kill and restart them.

**Comment by bonuzzz** [comment]
But if nobody connected to camera, it will restart processes every time with established...

**Comment by bonuzzz** [comment]
added new commit. replace process check from top to ps (pid checking)
and returned ESTABLISHED condition, but i'm not sure it's ever working because both processes should be have no activity (0.0 cpu) more than 1 minute. But this is only my thoughts because i can't redproduce this issue. Your firmware is very stable for me and i never had any hangs.

**Comment by roleoroleo** [comment]
> But if nobody connected to camera, it will restart processes every time with established...

This does not happen because the cpu load of the processes is always high.

**Comment by bonuzzz** [comment]
I said when nobody connected

**Comment by roleoroleo** [comment]
I don't understand, sorry.

> 
> 
> I said when nobody connected. not everyone uses camera all the time.
> 

If no one is connected and the processes are running the script doesn't enter in the first rule because of this condition:
`if [ "$CPU_1" == "" ] || [ "$CPU_2" == "" ]; then`
and the script doesn't enter in the second rule because of this condition:
`if [ $SOCKET -gt 0 ]; then`
then the processes are not killed.

> Anyway, in first rule https://github.com/roleoroleo/yi-hack-MStar/blob/master/src/static/static/home/yi-hack/script/wd_rtsp.sh#L41
> when you kill h264grabber process port 554 stays busy with rRTSPserver process and with ESTABLISHED status. (link to issue you mentioned before) and this rule doesn't work. So I think it's better to rewrite rule and control both processes independently without checking port

The script enters in the second rule only if there are no established connections, because of this condition:
`if [ $SOCKET -gt 0 ]; then`
The problem you described should not happen.

Anyway, I will check the script with some tests.

> i found sys file from original firmware. your link from italian forum. is original fw have only sys file?

The file you found is not the original firmware.

**Comment by roleoroleo** [comment]
Another detail.
I noticed that the command
`top -b -n 1 -d 1`
often returns the cpu to a value of 0
The command
`top -b -n 2 -d 1`
works better.

**Comment by bonuzzz** [comment]
> Another detail.
> I noticed that the command
> `top -b -n 1 -d 1`
> often returns the cpu to a value of 0
> The command
> `top -b -n 2 -d 1`
> works better.

but you use only the first result anyway (tail -n 1)

**Comment by roleoroleo** [comment]
> but you use only the first result anyway (tail -n 1)

You are right :)
I have to use the second line.

> just kill h264grabber.
Ok, this is correct.
If I am not wrong, after a timeout, the sockect closes and the process terminates.
Then, at the next run of the watchdog, the processes restart.

Later, I will try to rewrite the script tryng to detect if the process is running for high res or low res.

**Comment by bonuzzz** [comment]
https://gist.github.com/bonuzzz/277053814e30c361c6ae1c1dbdd5ad75
this is variant of script what i'm using now. it's not final and not perfect and have some experiments, but probably you'll have some ideas after seeing.
i use own binaries for each stream.  i have an idea to control low and res streams independently and control them from web interface. i can't pr it because i can't test build process for now.

**Comment by roleoroleo** [comment]
What do you think about 4 symlinks?

h264grabber_h
h264grabber_l
rRTSPServer_h
rRTSPServer_l

in this way it is not necessary to go through the process pid, cmdline, etc. etc. etc...
Like your solution with 2 binaries but without waste space.
Below the script:
```
#!/bin/sh

CONF_FILE="etc/system.conf"

YI_HACK_PREFIX="/home/yi-hack"

#LOG_FILE="/tmp/sd/wd_rtsp.log"
LOG_FILE="/dev/null"

COUNTER_H=0
COUNTER_L=0
COUNTER_LIMIT=10
INTERVAL=10

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lib:/home/yi-hack/lib:/tmp/sd/yi-hack/lib
export PATH=$PATH:/home/base/tools:/home/yi-hack/bin:/home/yi-hack/sbin:/tmp/sd/yi-hack/bin:/tmp/sd/yi-hack/sbin

get_config()
{
    key=$1
    grep -w $1 $YI_HACK_PREFIX/$CONF_FILE | cut -d "=" -f2
}

restart_rtsp()
{
    if [[ "$1" == "high" ]]; then
        if [[ $(get_config RTSP_STREAM) == "high" ]] || [[ $(get_config RTSP_STREAM) == "both" ]]; then
            h264grabber_h -r high | RRTSP_RES=0 RRTSP_PORT=$RTSP_PORT RRTSP_USER=$USERNAME RRTSP_PWD=$PASSWORD rRTSPServer_h &
        fi
    elif [[ "$1" == "low" ]]; then
        if [[ $(get_config RTSP_STREAM) == "low" ]] || [[ $(get_config RTSP_STREAM) == "both" ]]; then
            h264grabber_l -r low | RRTSP_RES=1 RRTSP_PORT=$RTSP_PORT RRTSP_USER=$USERNAME RRTSP_PWD=$PASSWORD rRTSPServer_l &
        fi
    fi
}

check_rtsp()
{
#  echo "$(date +'%Y-%m-%d %H:%M:%S') - Checking RTSP process..." >> $LOG_FILE
    SOCKET_H=`netstat -an 2>&1 | grep ":$RTSP_PORT " | grep ESTABLISHED | grep -c ^`
    CPU_1_H=`top -b -n 2 -d 1 | grep h264grabber_h | grep -v grep | tail -n 1 | awk '{print $8}'`
    CPU_2_H=`top -b -n 2 -d 1 | grep rRTSPServer_h | grep -v grep | tail -n 1 | awk '{print $8}'`

    SOCKET_L=`netstat -an 2>&1 | grep ":$RTSP_PORT_L " | grep ESTABLISHED | grep -c ^`
    CPU_1_L=`top -b -n 2 -d 1 | grep h264grabber_l | grep -v grep | tail -n 1 | awk '{print $8}'`
    CPU_2_L=`top -b -n 2 -d 1 | grep rRTSPServer_l | grep -v grep | tail -n 1 | awk '{print $8}'`

    if [ $SOCKET_H -eq 0 ]; then
        if [ "$CPU_1_H" == "" ] || [ "$CPU_2_H" == "" ]; then
            echo "$(date +'%Y-%m-%d %H:%M:%S') - No running processes for high res, restarting..." >> $LOG_FILE
            killall -q rRTSPServer_h
            killall -q h264grabber_h
            sleep 1
            restart_rtsp "high"
        fi
        COUNTER_H=0
    fi
    if [ $SOCKET_H -gt 0 ]; then
        if [ "$CPU_1_H" == "0.0" ] && [ "$CPU_2_H" == "0.0" ]; then
            COUNTER_H=$((COUNTER_H+1))
            echo "$(date +'%Y-%m-%d %H:%M:%S') - Detected possible locked process for high res ($COUNTER_H)" >> $LOG_FILE
            if [ $COUNTER_H -ge $COUNTER_LIMIT ]; then
                echo "$(date +'%Y-%m-%d %H:%M:%S') - Restarting processes for high res" >> $LOG_FILE
                killall -q rRTSPServer_h
                killall -q h264grabber_h
                sleep 1
                restart_rtsp "high"
                COUNTER_H=0
            fi
        else
            COUNTER_H=0
        fi
    fi

    if [ $SOCKET_L -eq 0 ]; then
        if [ "$CPU_1_L" == "" ] || [ "$CPU_2_L" == "" ]; then
            echo "$(date +'%Y-%m-%d %H:%M:%S') - No running processes for low res, restarting..." >> $LOG_FILE
            killall -q rRTSPServer_l
            killall -q h264grabber_l
            sleep 1
            restart_rtsp "low"
        fi
        COUNTER_L=0
    fi
    if [ $SOCKET_L -gt 0 ]; then
        if [ "$CPU_1_L" == "0.0" ] && [ "$CPU_2_L" == "0.0" ]; then
            COUNTER_L=$((COUNTER_L+1))
            echo "$(date +'%Y-%m-%d %H:%M:%S') - Detected possible locked process for low res ($COUNTER_L)" >> $LOG_FILE
            if [ $COUNTER_L -ge $COUNTER_LIMIT ]; then
                echo "$(date +'%Y-%m-%d %H:%M:%S') - Restarting processes for low res" >> $LOG_FILE
                killall -q rRTSPServer_l
                killall -q h264grabber_l
                sleep 1
                restart_rtsp "low"
                COUNTER_L=0
            fi
        else
            COUNTER_L=0
        fi
    fi
}

if [[ $(get_config RTSP) == "no" ]] ; then
    exit
fi

if [[ "$(get_config USERNAME)" != "" ]] ; then
    USERNAME=$(get_config USERNAME)
    PASSWORD=$(get_config PASSWORD)
fi

case $(get_config RTSP_PORT) in
    ''|*[!0-9]*) RTSP_PORT=554 ;;
    *) RTSP_PORT=$(get_config RTSP_PORT) ;;
esac
case $(get_config RTSP_PORT_L) in
    ''|*[!0-9]*) RTSP_PORT_L=8554 ;;
    *) RTSP_PORT_L=$(get_config RTSP_PORT_L) ;;
esac

echo "$(date +'%Y-%m-%d %H:%M:%S') - Starting RTSP watchdog..." >> $LOG_FILE

while true
do
    check_rtsp
    if [ $COUNTER_H -eq 0 ] && [ $COUNTER_L -eq 0 ]; then
        sleep $INTERVAL
    fi
done
```

**Comment by bonuzzz** [comment]
> What do you think about 4 symlinks?
you will see original process name in top unfortunately

**Comment by roleoroleo** [comment]
I tried and I see the link name:

```
Mem: 59880K used, 944K free, 4384K shrd, 700K buff, 13036K cached
CPU: 26.7% usr 35.3% sys  0.0% nic 33.4% idle  0.0% io  0.0% irq  4.3% sirq
Load average: 2.17 1.96 1.89 1/141 2486
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  149     1 root     S    47048 76.9   0 33.0 ./rmm
 2435  2328 root     S     2692  4.4   0  5.7 h264grabber_l
 2362   629 root     S     2692  4.4   0  5.6 h264grabber -r high
 2363   629 root     S     4108  6.7   0  4.0 rRTSPServer
 2438  2328 root     R     2060  3.3   0  0.5 top
    7     2 root     SW       0  0.0   0  0.5 [rcu_preempt]
  437     1 root     S    12700 20.7   0  0.3 ./p2p_tnp
 2304   495 root     S     2012  3.2   0  0.3 dropbear -R
    3     2 root     SW       0  0.0   0  0.3 [ksoftirqd/0]
  435     1 root     S     7648 12.5   0  0.1 ./mp4record
  140     1 root     S     5060  8.2   0  0.1 ./dispatch
```

**Comment by bonuzzz** [comment]
> I tried and I see the link name:

hm.. that's interesting. i tried before and saw only parent name
about size, yes, you're right. 12mb is total partition size.
if symlinks work, it will be very good.

**Comment by roleoroleo** [comment]
Added to the PR https://github.com/roleoroleo/yi-hack-MStar/pull/113

**Pull request closed without merging**
