### PR TITLE
Audio replicator with noise reduction 16khz

### PR DESCRIPTION
**Pull request by PieVo**
Replaces https://github.com/roleoroleo/yi-hack-MStar/pull/185
Information: https://github.com/roleoroleo/yi-hack-MStar/issues/194

This clones the audio fifo and make it available to 3 streams for one single rRTSPServer instance. The H264 grabbers dump their video into pipes which are read by the rRTSP server.

- Implements noise reduction based on existing libraries in the camera
- Implements a replicator, so audio can be used for all streams
- Implements an audio only stream

High + Audio:
Play this stream using the URL "rtsp://192.168.3.180/ch0_0.h264"

Low + Audio:
Play this stream using the URL "rtsp://192.168.3.180/ch0_1.h264"

Audio only:
Play this stream using the URL "rtsp://192.168.3.180/ch0_2.h264"

### CODE REVIEW

**Comment by roleoroleo** [comment]
Thanks for your pr.
I will work on this the next week.

**Comment by roleoroleo** [comment]
I'm trying to build your branch but I have a compilation error about mkfifo:
```
MOD_DIR:        /home/user/yi/PieVo/yi-hack-MStar/src/mkfifo
MOD_NAME:       mkfifo
MOD_INIT:       init.mkfifo
MOD_COMPILE:    compile.mkfifo
MOD_INSTALL:    install.mkfifo
init.mkfifo not found.. exiting.
```

I think beacuse you didn't create the structucre init/compile/install in the mkfifo directory.
Is mkfifo required?
If it's required, could we add it to busybox and avoid to build it externally?

**Comment by PieVo** [comment]
The mkfifo is indeed required, since I didnt want to touch the h264grabbers... The goal of the PR is to create 2 fifos where the low and high grabbers can dump their data in. The (single) RTSP server instance reads the data from there.

My mkfifo was just a makeshift mkfifo the get it working. Of course the busybox one is preferred. Do we have our own busybox?

**Comment by roleoroleo** [comment]
> My mkfifo was just a makeshift mkfifo the get it working. Of course the busybox one is preferred. Do we have our own busybox?

Yes, you could simply change
# CONFIG_MKFIFO is not set
in
CONFIG_MKFIFO=y

inside src/busybox/.config

**Comment by roleoroleo** [comment]
I have a problem starting rtsp server.
When I start h264grabber and then rRTSPServer the system is blocked on the fifo.
I have to read some data to start the chain.
Do you have this problem?

**Comment by PieVo** [comment]
Hi, I’ve been running my test-code for a while without reboots so I could
not witness this behavior. I can have a look tonight, do you perhaps have a
test branch?

Is this purely (one of) the video fifos? So indeed the fifo behavior is
that the “writer open” blocks until a reader opens the others end.. That
should happen when rRTSPserver starts and opens the fifo to check the file
for its length. Does opening the rtsp stream also work for unblocking?

Since the grabbers are completely detached from rmm I don’t expect any
deadlocks there.

What is the sequence that you have now?
Rmm
Mkfifos
Grabbers
Rtsp server

Perhaps the grabbers did not reach opening the fifo for write and the rtsp
is already starting? (Because of the & process spawn)





Op zo 12 jul. 2020 om 17:20 schreef roleo <notifications@github.com>

**Comment by roleoroleo** [comment]
The sequence is:

- rmm
- mkfifo
- h264grabber
- rRTSPServer

When I start h264_grabber_h.sh the system blocks and when I play vlc doesn't restart.
Don't worry, I solved adding mkfifo inside h264grabber code, it works (I don't know why but it works).
I merged your pr and I'm editing some files to adapt your changes.

**Comment by roleoroleo** [comment]
I merged my changes, if you want to try.
Major differences from your version:

- Add mkfifo to busybox and removed from src (not necessary, see next step).
- Move mkfifo inside h264grabber code.
- Change RTSP_AUDIO option to a checkbox.
- Change system.sh and wd_rtsp.sh to manage new binary.
- Remove h264_grabber_high.sh and h264_grabber_low.sh.

**Comment by PieVo** [comment]
Just checked the code here and there, lots of changes to the config! Too much for me to patch manually on top of a running 0.3.4 fw. 

Making a full build now (on a slow machine)...

**Comment by roleoroleo** [comment]
Sorry but github isn't my best.

**Comment by PieVo** [comment]
So, I'm wondering if my build is good (I don't have the original FW files, but used already released ones).. Since the camera is actually used, I don't want to brick it. Would it be possible to share your build, so I know it at least boots?

**Comment by roleoroleo** [comment]
Which model suffix?
I don't remember.

**Comment by PieVo** [comment]
Sorry, forgot to mention.. I have the y203 (6FUS).

Op wo 15 jul. 2020 om 10:47 schreef roleo <notifications@github.com>

**Comment by roleoroleo** [comment]
Here it is:
[y203c_0.3.4.tar.gz](https://github.com/roleoroleo/yi-hack-MStar/files/4924107/y203c_0.3.4.tar.gz)

I suggest to reconfigure the cam from scratch.

**Comment by PieVo** [comment]
Great! got it running... 
Also audio only: rtsp://192.168.3.180/ch0_2.h264 is working fine...

Regarding the settings there might be a little quirk:
- Just before upgrading firmware I reset the camera defaults...
- Upgraded firmware
- Enable audio & restart --> No
- Reset to defaults again -> Audio is enable (rRTSPserver_audio is running)
- However the flag in the config is set to disabled :)


If you see time, and perhaps in a different PR, the setting for the noise reduction could also be configurable... With 0 it is completely off, which saves some cpu performance.

**Comment by roleoroleo** [comment]
I will check the flag, thank you.
Probably the change from select object to checkbox object.
Could you share your system.conf?

**Comment by PieVo** [comment]
/home/yi-hack # cat ./etc/system.conf
HTTPD=yes
TELNETD=no
SSHD=yes
FTPD=yes
BUSYBOX_FTPD=no
DISABLE_CLOUD=no
REC_WITHOUT_CLOUD=no
MQTT=no
RTSP=yes
RTSP_STREAM=both
RTSP_AUDIO=yes
ONVIF=yes
ONVIF_WSDD=yes
ONVIF_PROFILE=high
ONVIF_WM_SNAPSHOT=yes
NTPD=yes
NTP_SERVER=pool.ntp.org
PROXYCHAINSNG=no
RTSP_PORT=554
ONVIF_PORT=80
HTTPD_PORT=8080
USERNAME=
PASSWORD=
FREE_SPACE=0
FTP_UPLOAD=no
FTP_HOST=
FTP_USERNAME=
FTP_PASSWORD=
SSH_PASSWORD=

**Comment by roleoroleo** [comment]
RTSP_AUDIO is ok.

Try to call configuration web service:
http://IP:8080/cgi-bin/get_configs.sh?conf=system

Do you clean the cache?

**Comment by PieVo** [comment]
Its indeed the cache, other browsers show the toggle in the right position..

**Comment by roleoroleo** [comment]
Ok. Damn cache...

**Pull request merged**
